// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'RestClient.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

pmData _$pmDataFromJson(Map<String, dynamic> json) => pmData(
      stationName: json['stationName'] as String?,
      sidoName: json['sidoName'] as String?,
      dataTime: json['dataTime'] as String?,
      o3Value: json['o3Value'] as String?,
      pm10Value: json['pm10Value'] as String?,
    );

Map<String, dynamic> _$pmDataToJson(pmData instance) => <String, dynamic>{
      'stationName': instance.stationName,
      'sidoName': instance.sidoName,
      'dataTime': instance.dataTime,
      'o3Value': instance.o3Value,
      'pm10Value': instance.pm10Value,
    };

TestModel _$TestModelFromJson(Map<String, dynamic> json) => TestModel(
      response: json['response'],
    );

Map<String, dynamic> _$TestModelToJson(TestModel instance) => <String, dynamic>{
      'response': instance.response,
    };

Autogenerated _$AutogeneratedFromJson(Map<String, dynamic> json) =>
    Autogenerated(
      response: json['response'] == null
          ? null
          : Response.fromJson(json['response'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$AutogeneratedToJson(Autogenerated instance) =>
    <String, dynamic>{
      'response': instance.response,
    };

// **************************************************************************
// RetrofitGenerator
// **************************************************************************

class _RestClient implements RestClient {
  _RestClient(this._dio, {this.baseUrl}) {
    baseUrl ??= 'http://apis.data.go.kr';
  }

  final Dio _dio;

  String? baseUrl;

  @override
  Future<TestModel> getData(serviceKey, sidoName, json) async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{
      r'serviceKey': serviceKey,
      r'sidoName': sidoName,
      r'returnType': json
    };
    final _headers = <String, dynamic>{
      r'Accept': 'application/json',
      r'content-type': 'application/json'
    };
    _headers.removeWhere((k, v) => v == null);
    final _data = <String, dynamic>{};
    final _result = await _dio.fetch<Map<String, dynamic>>(
        _setStreamType<TestModel>(Options(
                method: 'GET',
                headers: _headers,
                extra: _extra,
                contentType: 'application/json')
            .compose(_dio.options,
                '/B552584/ArpltnInforInqireSvc/getCtprvnRltmMesureDnsty',
                queryParameters: queryParameters, data: _data)
            .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl)));
    final value = TestModel.fromJson(_result.data!);
    return value;
  }

  @override
  Future<Autogenerated> getJson(
      serviceKey, sidoName, json, numOfRows, pageNo) async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{
      r'serviceKey': serviceKey,
      r'sidoName': sidoName,
      r'returnType': json,
      r'numOfRows': numOfRows,
      r'pageNo': pageNo
    };
    final _headers = <String, dynamic>{
      r'Accept': 'application/json',
      r'content-type': 'application/json'
    };
    _headers.removeWhere((k, v) => v == null);
    final _data = <String, dynamic>{};
    final _result = await _dio.fetch<Map<String, dynamic>>(
        _setStreamType<Autogenerated>(Options(
                method: 'GET',
                headers: _headers,
                extra: _extra,
                contentType: 'application/json')
            .compose(_dio.options,
                '/B552584/ArpltnInforInqireSvc/getCtprvnRltmMesureDnsty',
                queryParameters: queryParameters, data: _data)
            .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl)));
    final value = Autogenerated.fromJson(_result.data!);
    return value;
  }

  RequestOptions _setStreamType<T>(RequestOptions requestOptions) {
    if (T != dynamic &&
        !(requestOptions.responseType == ResponseType.bytes ||
            requestOptions.responseType == ResponseType.stream)) {
      if (T == String) {
        requestOptions.responseType = ResponseType.plain;
      } else {
        requestOptions.responseType = ResponseType.json;
      }
    }
    return requestOptions;
  }
}
